# This starter workflow for running ros2 jazzy

name: orpheus_project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  my_build:
    runs-on: ubuntu-latest
    
    container:
      image: ros:jazzy
      options: --user root

      env:
        # ORPHEUS_BUILD_DIR: ${{github.workspace}}/orpheus_ocean
        ROS_DISTRO: jazzy
        DEBIAN_FRONTEND: noninteractive

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dependencies
        run: |
          apt-get update && apt-get install -y \
            ros-${ROS_DISTRO}-imu-tools \
            ros-${ROS_DISTRO}-ament-cmake-test \
            python3-rosdep
          mkdir -p src
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      - name: build and test
        shell: bash
        run: |
          source /opt/ros/${ROS_DISTRO}/setup.sh
          colcon build
          source install/local_setup.sh
          colcon test  --rerun-failed --output-on-failure
          colcon test-result --verbose

      # - name: Run orpheus tests
      #   shell: bash
      #   run: |
      #     source install/local_setup.sh
      #     colcon test
      #     colcon test-result --verbose
